clock_period = 1; 
sample_delay = 0.2 * clock_period;
sampling_frequency = 1000;
t = 0:0.01:10*clock_period;
clock_signal = square(2*pi*t/clock_period, 50);
received_signal =sin(2*pi*t/clock_period);
early_clock = square(2*pi*(t -sample_delay)/clock_period, 50);
late_clock = square(2*pi*(t +sample_delay)/clock_period, 50);
early_output = early_clock .*received_signal;
late_output = late_clock .*received_signal;
early_integral = trapz(t,early_output);
late_integral = trapz(t,late_output);
disp(['Early Integral: ',num2str(early_integral)]);
disp(['Late Integral: ',num2str(late_integral)]);
sampling_instants =0:1/sampling_frequency:t(end);
early_samples = interp1(t,early_output, sampling_instants,'linear', 0);
late_samples = interp1(t,late_output, sampling_instants,'linear', 0);
early_magnitude = abs(early_samples);
late_magnitude = abs(late_samples);
combined_magnitude = early_magnitude+ late_magnitude;
combined_magnitude =interp1(sampling_instants,combined_magnitude, t, 'linear', 0);
modulated_clock_signal = clock_signal.* (1 + combined_magnitude);
figure;
subplot(4,1,1);
plot(t, clock_signal);
title('Clock Signal');
subplot(4,1,2);
plot(t, received_signal);
title('Received Signal');
subplot(4,1,3);
plot(t, early_output);
title('Early Output (Multiplied with Received Signal)');
subplot(4,1,4);
plot(t, late_output);
title('Late Output (Multiplied with Received Signal)');
figure;
subplot(3,1,1);
stem(sampling_instants,early_samples);
title('Sampled Early Output');
subplot(3,1,2);
stem(sampling_instants,late_samples);
title('Sampled Late Output');
subplot(3,1,3);
plot(t, modulated_clock_signal);
title('Modulated Clock Signal');
